# Generated by Django 5.0 on 2025-07-03 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_student_profile_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='educational_institution',
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
    ]
