# Generated by Django 5.0 on 2025-07-03 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_student_educational_institution'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='educational_institution',
        ),
    ]
